<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Component\Utility\UrlHelper;

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;





function kogan_book_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'contact_message_feedback_form') {
  }

	if ($form_id == 'user_register_form') {
    $form['field_monthly']['widget'][0]['value']['#title']= t('Dailling code');    
	  $form['actions']['submit']['#submit'][] = 'oil_survey_contact_submit';
	  $form['actions']['submit']['#value'] = t('Next step');
    $form['account']['mail']['#description'] = t('');
    $form['account']['pass']['#description'] = t('');
    $form['account']['mail']['#attributes']['placeholder'] = t('please fill...');
  }

  if ($form_id == 'contact_message_feedback_form') {
    $form['name']['#plain_text'] = t('');
    $form['mail']['#plain_text'] = t('');
    $form['name']['#type'] = 'textfield';
    $form['mail']['#type'] = 'textfield';
    $form['name']['#value'] = t('');
    $form['mail']['#value'] = t('');
  }

}

 function register_alter_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
     case 'user_register_form':
       $form['account']['pass']['#process'][] = array('form_process_password_confirm', 'register_alter_password_confirm');
       
  }
  
	
}


// function kogan_book_contact_submit($form, \Drupal\Core\Form\FormStateInterface &$form_state) {
//   $host = \Drupal::request()->getHost();
//   $url = Url::fromUri('http://' . $host . '/questionary');
//   $form_state->setRedirectUrl($url);
// }


function kogan_book_theme($existing, $type, $theme, $path) {
  
  return array(    
    'page_result' => array(
      'variables' => array(
        'frontx' => null,
        'backx' => null,
        'monetx' => null,
        'fronty' => null,
        'backy' => null,
        'monety' => null,
        'targetx' => null,
        'targety' => null,
        ),
      'template' => 'page_result',
    ),     

    // 'top_header_block' => array(
    //   'variables' => array(
    //     'items' => null,
    //     ),
    //   'template' => 'top_header_block',
    // ),         
    
    'content_block' => array(
      'template' => 'content_block',
      'variables' => array(
        'items' => null,
        'items1' => null,
        'items2' => null,
        'itemsy' => null,
	      'itemsy1' => null,
	      'itemsy2' => null,
	      'itemsz1' => null,
      	'itemsz2' => null,
      ),
    ),

    'footer_block' => array(
      'variables' => array(
        'items' => null,
      ),
      'template' => 'footer_block',
    ),
  );
}
