<?php


  use Drupal\Core\Mail\MailManagerInterface;
  use Drupal\Component\Utility\SafeMarkup;
  use Drupal\Component\Utility\Html;
  use Drupal\node\Entity\Node;
  use Drupal\file\Entity\File;
  use Drupal\Core\Form\FormStateInterface;
  use Drupal\Core\Url;



  function feedback_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {

    if ($form_id == 'question_form') {
       $form['#submit'][] = 'comment_discussion_comment_delete_submit'; 
    }
   
  }


  function comment_discussion_comment_delete_submit(array $form, FormStateInterface $form_state) {
    $image = new Imagick();
    $image->readImageBlob(file_get_contents('images/chart.svg'));
    $image->setImageFormat("png24");
    // if(file_exists('chart.png')) {
    //   $i = 1;
    //   $i=$i + 1;
    //   $image->writeImage('chart'.$i.'.png');
    // }
    $name = 'chart.png';
    $actual_name = pathinfo($name,PATHINFO_FILENAME);
    $original_name = $actual_name;
    $extension = pathinfo($name, PATHINFO_EXTENSION);

    $i = 1;
    while(file_exists('images/'.$actual_name.".".$extension))
    {           
        $actual_name = (string)$original_name.$i;
        $name = $actual_name.".".$extension;
        $i++;
    }

    $image->writeImage('images/'.$name.'');

    $host = \Drupal::request()->getHost();
    $url_image = 'http://' . $host . '/images/chart-default.png';
    \Drupal::state()->set('imageresult', $url_image);
    
    // function imageExists($image,$dir) {

    //   $i=1; $probeer= $image;

    //   while(file_exists($dir.$probeer)) {
    //       kint($dir);
    //       die();
    //       $punt=strrpos($image,".");
    //       if(substr($image,($punt-3),1)!==("[") && substr($image,($punt-1),1)!==("]")) {
    //           $probeer=substr($image,0,$punt)."[".$i."]".
    //           substr($image,($punt),strlen($image)-$punt);
    //       } else {
    //           $probeer=substr($image,0,($punt-3))."[".$i."]".
    //           substr($image,($punt),strlen($image)-$punt);
    //       }
    //       $i++;        
    //   }
    //   // $image->writeImage(''.$probeer.'.png');
    //   return $probeer;
    // }



  }

  /**
   * Implements hook_mail().s
   */

  function feedback_form_mail($key, &$message, $params) {
    $val['imageresult'] = \Drupal::state()->get('imageresult');
    $images = $val['imageresult'];
    $options = array (
      'langcode' => $message['langcode'],
    );
    switch ($key) {
      case 'comment_alert_mail':
        $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
        $message['from'] = \Drupal::config('system.site')->get('mail');
        $message['subject'] = t('@title ', array(
            '@title' => $params['node_title'],
           ),
          $options);
        $theme_body = array (
          '#theme' => 'comment_alert_mail',
          '#text' => $images,
          '#title' => $params['node_title'],
        );
        $mail_body = drupal_render($theme_body);
        $message['body'][] = Html::escape($mail_body);
        break;
    };
  }

  /**
   * Implements hook_entity_insert().
   */

  function feedback_form_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
    if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'questionnaire')) {
      return;
    }
    $key = 'comment_alert_mail';
    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'feedback_form';  
    $to = $entity->get('title')->value;
    $params['node_title'] = 'Kogan book';
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = true;
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);

  }


  /**
   * Implements hook_theme().
   */

  function feedback_form_theme() { 
    $keys = [
    'frontx',
    'backx',
    'monetx',
    'fronty',
    'backy',
    'monety',
    'targetx',
    'targety',
    'arrowx1',
    'arrowy1',
    'arrowx2',
    'arrowy2',
    'question1',
    'question2',
    'question3',
    'question4',
    'question5',
    'question6',
    'question7',
    'question8',
    'question9',
    'question10',
    'question11',
    'question12',
    'question13',
    'question14',
    'question15',
    'question101',
    'question102',
    'question103',
    'question104',
    'question105',
    'question106',
    'question107',
    'question108',
    'question109',
    'question110',
    'question111',
    'question112',
    'question113',
    'question114',
    'imageresult',
  ];

  $val = \Drupal::state()->getMultiple($keys);
  $variables['imageresult'] = $val['imageresult'];
  $variables['frontx'] = $val["frontx"];
  $variables['backx'] = $val['backx'];
  $variables['monetx'] = $val['monetx'];
  $variables['fronty'] = $val['fronty'];
  $variables['backy'] = $val['backy'];
  $variables['monety'] = $val['monety'];
  $variables['targetx'] = $val['targetx'];
  $variables['targety'] = $val['targety'];
  $variables['arrowx1'] = $val['arrowx1'];
  $variables['arrowy1'] = $val['arrowy1'];
  $variables['arrowx2'] = $val['arrowx2'];
  $variables['arrowy2'] = $val['arrowy2'];
  $variables['question1'] = $val['question1'];
  $variables['question2'] = $val['question2'];
  $variables['question3'] = $val['question3'];
  $variables['question4'] = $val['question4'];
  $variables['question5'] = $val['question5'];
  $variables['question6'] = $val['question6'];
  $variables['question7'] = $val['question7'];
  $variables['question8'] = $val['question8'];
  $variables['question9'] = $val['question9'];
  $variables['question10'] = $val['question10'];
  $variables['question11'] = $val['question11'];
  $variables['question12'] = $val['question12'];
  $variables['question13'] = $val['question13'];
  $variables['question14'] = $val['question14'];
  $variables['question15'] = $val['question15'];
  $variables['question101'] = $val['question101'];
  $variables['question102'] = $val['question102'];
  $variables['question103'] = $val['question103'];
  $variables['question104'] = $val['question104'];
  $variables['question105'] = $val['question105'];
  $variables['question106'] = $val['question106'];
  $variables['question107'] = $val['question107'];
  $variables['question108'] = $val['question108'];
  $variables['question109'] = $val['question109'];
  $variables['question110'] = $val['question110'];
  $variables['question111'] = $val['question111'];
  $variables['question112'] = $val['question112'];
  $variables['question113'] = $val['question113'];
  $variables['question114'] = $val['question114'];
  $frontx = $val["frontx"];
  $fronty = $val['fronty'];
  $backx = $val['backx'];
  $monetx = $val['monetx'];
  $backy = $val['backy'];
  $monety = $val['monety'];
  $frontx2 = 5*$val["frontx"];
  $fronty2 = 5.07*$val['fronty'];
  $backx2 = 5*$val['backx'];
  $monetx2 = 5*$val['monetx'];
  $backy2 = 5.07*$val['backy'];
  $monety2 = 5.07*$val['monety'];
  $targetx2 = 5*$val['targetx'];
  $targety2 = 5.07*$val['targety'];
  $targetx = $val['targetx'];
  $targety = $val['targety'];
  $arrowx1 = $val['arrowx1'];
  $arrowy1 = $val['arrowy1'];
  $arrowx2 = $val['arrowx2'];
  $arrowy2 = $val['arrowy2'];
  $arrowx3 = $arrowx1*5;
  $arrowy3 = $arrowy1*5.07;
  $arrowx4 = $arrowx2*5;
  $arrowy4 = $arrowy2*5.07;
  $targetx12 = $targetx2 + 2.5;
  $targetx13 = $targetx2 + 1.732;
  $targetx14 = $targetx2 + 5;
  $targetx18 = $targetx2 - 2.5;
  $targetx19 = $targetx2 - 1.732;
  $targetx20 = $targetx2 -5;
  $targety11 = $targety2 + 2;
  $targety12 = $targety2 + 4.33;
  $targety13 = $targety2 + 1;
  $targety15 = $targety2 - 1;
  $targety16 = $targety2 - 4.33;
  $targety17 = $targety2 - 2;
  

  return [
    'icon' => [
      'variables' => [
        'arrowx1' => null,
        'arrowy1' => null,
        'arrowx2' => null,
        'arrowy2' => null,
        'frontx' => null,
        'backx' => null,
        'monetx' => null,
        'fronty' => null,
        'backy' => null,
        'monety' => null,
        'targetx' => null,
        'targety' => null,
        'feedback' => null,
        'question1' => null,
        'question2' => null,
        'question3' => null,
        'question4' => null,
        'question5' => null,
        'question6' => null,
        'question7' => null,
        'question8' => null,
        'question9' => null,
        'question10' => null,
        'question11' => null,
        'question12' => null,
        'question13' => null,
        'question14' => null,
        'question15' => null,
        'question101' => null,
        'question102' => null,
        'question103' => null,
        'question104' => null,
        'question105' => null,
        'question106' => null,
        'question107' => null,
        'question108' => null,
        'question109' => null,
        'question110' => null,
        'question111' => null,
        'question112' => null,
        'question113' => null,
        'question114' => null,
      ],
    ],

    'comment_alert_mail' => [
      'variables' => [
        'text' => null,
        'arrowx1' => null,
        'arrowy1' => null,
        'arrowx2' => null,
        'arrowy2' => null,
        'frontx' => null,
        'backx' => null,
        'monetx' => null,
        'fronty' => null,
        'backy' => null,
        'monety' => null,
        'targetx' => null,
        'targety' => null,
        'feedback' => null,
        'question1' => null,
        'question2' => null,
        'question3' => null,
        'question4' => null,
        'question5' => null,
        'question6' => null,
        'question7' => null,
        'question8' => null,
        'question9' => null,
        'question10' => null,
        'question11' => null,
        'question12' => null,
        'question13' => null,
        'question14' => null,
        'question15' => null,
        'question101' => null,
        'question102' => null,
        'question103' => null,
        'question104' => null,
        'question105' => null,
        'question106' => null,
        'question107' => null,
        'question108' => null,
        'question109' => null,
        'question110' => null,
        'question111' => null,
        'question112' => null,
        'question113' => null,
        'question114' => null,
        'imageresult' => null,
      ],
    ],
  ];
  }